NEWS_API_KEY = "your_api_key"
NEWS_API_URL = "https://newsapi.org/v2/top-headlines"
ELASTICSEARCH_HOST = "http://localhost:9200"
REDIS_BROKER = "redis://localhost:6379/0"
REDIS_BACKEND = "redis://localhost:6379/0"
INDEX_NAME = "news_articles"